#x=input('x;')
#y=input('y;')
#print(int(x)-int(y))
#print(isinstance(x,int))
#print(isinstance(x,str))
#name=print(input('siznig yiliniz'))
#age=print(2025-+name)
#print("siznig yoshingiz;"+age)
#yearnow=input('hozirgi yil;')
#bith=input('siznig yiliniz;')
#age=int(yearnow)-int(bith)
#print('sizning yoshingiz;'+str(age))